language: go
go: '1.10'
install:
- make setup
script:
- make ci
after_success:
- make embed-assets
- bash <(curl -s https://codecov.io/bash)
notifications:
  email: false
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL http://git.io/goreleaser | bash
  on:
    tags: true
env:
  global:
    secure: TABQmooYR7glJgMksfjvZVf+uaRBONHSfRMPFJV723ENnlfnMUAhLcCAr7J5LHdj4DJzZURLAj7dLXJMqHBePG7jIJR82QdXnjYfDxCQsc1HB4pH1aD5G2VY8I3qJXMf0kkIV5PyHCZkXYy7KG5b7//Sn5pnZT2/hcHNguUdTWI3Ml9JtiIWuKC8aQF+/30ohoRnPeB3sWx8xeuosKFMdzoQgYuoK9yPZcFcZmXA7vbhZcqZfHEjigZ89dnOI0B2wHqmEeH9rbNcU9+AsgPv+hQBTzKgaM5VP6zUfnfX2nnkRc2HX6kMdbrbTq027eq22SMhbCJaebB48J0AhcSo7HqOZuz+tlwxtXoU12cxZWQZOQ5f9OpogSClfMA0KipeXvdyDIwzJtiOmxaaeNbJWw9lVcAptDX5aCPoW3on1qQsW83mEPXqrTRJJdk7NxSr9jnvV/qiA7NnNQ7eRITi4owteRaTw3q4F8kcZip9hzfJPwVnSA6P6Vki8gQuF88Q+kXCiwj1eTNyakBFpFzZ9aJkEn4AcMjMd7t33TN+DcUf5o/b7edUO7q2Pn5yYFMsrKuXrkGFuNeOiTrCEn1XSfqhhqwX0s23wwMcGzIE+SIqmzCCx7w1WocpH37v7vb6Ajt0hTC4khSFet8pO+YISIh6hLspmbU1tRuvBZR93Bc=
